export const publicEmailProviders = [
  { company: 'Google', mail: 'gmail.com' },
  { company: 'Google', mail: 'googlemail.com' },
  { company: 'Yahoo', mail: 'yahoo.com' },
  { company: 'Yahoo UK', mail: 'yahoo.co.uk' },
  { company: 'Yahoo India', mail: 'yahoo.co.in' },
  { company: 'Yahoo', mail: 'ymail.com' },
  { company: 'Yahoo', mail: 'rocketmail.com' },
  { company: 'Microsoft Outlook', mail: 'outlook.com' },
  { company: 'Microsoft Outlook', mail: 'outlook.co.uk' },
  { company: 'Microsoft Hotmail', mail: 'hotmail.com' },
  { company: 'Microsoft Hotmail', mail: 'hotmail.co.uk' },
  { company: 'Microsoft Live', mail: 'live.com' },
  { company: 'Microsoft MSN', mail: 'msn.com' },
  { company: 'AOL', mail: 'aol.com' },
  { company: 'Apple iCloud', mail: 'icloud.com' },
  { company: 'Apple iCloud', mail: 'me.com' },
  { company: 'Apple iCloud', mail: 'mac.com' },
  { company: 'ProtonMail', mail: 'protonmail.com' },
  { company: 'Tutanota', mail: 'tutanota.com' },
  { company: 'Zoho', mail: 'zoho.com' },
  { company: 'Mail.com', mail: 'mail.com' },
  { company: 'GMX', mail: 'gmx.com' },
  { company: 'FastMail', mail: 'fastmail.com' },
  { company: 'HushMail', mail: 'hushmail.com' },
  { company: 'Inbox', mail: 'inbox.com' },
  { company: 'Mailfence', mail: 'mailfence.com' },
  { company: 'Posteo', mail: 'posteo.de' },
  { company: 'Lavabit', mail: 'lavabit.com' },
  { company: 'Runbox', mail: 'runbox.com' },
  { company: 'Seznam', mail: 'seznam.cz' },
  { company: 'Centrum', mail: 'centrum.cz' },
  { company: 'Volny', mail: 'volny.cz' },
  { company: 'Web.de', mail: 'web.de' },
  { company: 'Freenet', mail: 'freenet.de' },
  { company: 'GMX Germany', mail: 'gmx.de' },
  { company: '126 Mail', mail: '126.com' },
  { company: '163 Mail', mail: '163.com' },
  { company: 'Sina Mail', mail: 'sina.com' },
  { company: 'QQ Mail', mail: 'qq.com' },
  { company: 'Alibaba Mail', mail: 'aliyun.com' },
  { company: 'Yeah.net', mail: 'yeah.net' },
  { company: 'QQ Mail', mail: 'vip.qq.com' },
  { company: 'Mail.ru', mail: 'mail.ru' },
  { company: 'Mail.ru', mail: 'inbox.ru' },
  { company: 'Mail.ru', mail: 'bk.ru' },
  { company: 'Mail.ru', mail: 'list.ru' },
  { company: 'Yandex', mail: 'ya.ru' },
  { company: 'Rambler', mail: 'rambler.ru' },
  { company: 'Yandex', mail: 'yandex.ru' },
  { company: 'Yandex', mail: 'yandex.com' },
  { company: 'AT&T', mail: 'att.net' },
  { company: 'Verizon', mail: 'verizon.net' },
  { company: 'BellSouth', mail: 'bellsouth.net' },
  { company: 'Comcast', mail: 'comcast.net' },
  { company: 'Cox', mail: 'cox.net' },
  { company: 'Shaw', mail: 'shaw.ca' },
  { company: 'Rogers', mail: 'rogers.com' },
  { company: 'Telus', mail: 'telus.net' },
  { company: 'BT Internet', mail: 'btinternet.com' },
  { company: 'Tiscali', mail: 'tiscali.co.uk' },
  { company: 'Virgin Media', mail: 'virginmedia.com' },
  { company: 'Libero', mail: 'libero.it' },
  { company: 'Email.it', mail: 'email.it' },
  { company: 'Alice', mail: 'alice.it' },
  { company: 'Wanadoo', mail: 'wanadoo.fr' },
  { company: 'Orange', mail: 'orange.fr' },
  { company: 'Laposte', mail: 'laposte.net' },
  { company: 'SFR', mail: 'sfr.fr' },
  { company: 'Alice ADSL', mail: 'aliceadsl.fr' },
  { company: 'NTLWorld', mail: 'ntlworld.com' },
  { company: 'BT Openworld', mail: 'btopenworld.com' },
  { company: 'TalkTalk', mail: 'talktalk.net' },
  { company: 'Zoznam', mail: 'zoznam.sk' },
  { company: 'OptusNet', mail: 'optusnet.com.au' },
  { company: 'BigPond', mail: 'bigpond.com' },
  { company: 'Live UK', mail: 'live.co.uk' },


  { company: 'Mailinator', mail: 'mailinator.com' },
  { company: '10 Minute Mail', mail: '10minutemail.com' },
  { company: 'TempMail', mail: 'tempmail.net' },
  { company: 'Guerrilla Mail', mail: 'guerrillamail.com' },
];
